### ISSUE TITLE
Does not support xlsx

### ISSUE THREAD

**Issue by hanstsangcwc** [alephdata/convert-document#10]
It show "PDF export not supported."
When i try to curl an excel file, but word file works fine.

Thank you

Have a nice day

**Comment by pudo** [comment]
That's correct, we're not using this for tabular data and thus haven't built in support. What's your use case? 

Maybe https://github.com/thecodingmachine/gotenberg supports this?

**Comment by hanstsangcwc** [comment]
I recently dockerize my system, but there are some excel file need to export as PDF (with some pretty format).

I normally exec 
```
soffice --headless --convert-to pdf input_path --outdir output_path
```
I am just looking for something similar docker image that could handle excel to pdf.

Thank you

**Comment by hanstsangcwc** [comment]
i think gotenberg works, thank you very much
