### ISSUE TITLE
Feature request: Convert from PDF to other files?

### ISSUE THREAD

**Issue by tandat2209** [alephdata/convert-document#5]
Let's say we provide `outputFormat` params.

`outputFormat` could be `png` `jpg` from `.pdf` file.

**Comment by pudo** [comment]
Hey @tandat2209 !

Two comments: 

1. Have you checked out https://github.com/thecodingmachine/gotenberg ? They seem to be doing a ton more formats and might be a more flexible solution. I'm even wondering if we should use that. 

2. When you convert a Word document to a PNG image, what is the result? A picture of the first page of the document, or a picture of each page of the document? What is the resolution of the image?

**Comment by tandat2209** [comment]
1. That's great! I'll take a look at that.
2. What I would like is to convert a picture of all pages of the document. But the result when using LibreOffice is just the first page. Any solution to that?

**Comment by pudo** [comment]
Maybe you could convert to TIFF instead of PNG. As far as I know, TIFF is the only image format that supports multi-page images (which is super weird, but hey).
