### ISSUE TITLE
pdf name is displaying Ahmed Yousry

### ISSUE THREAD

**Issue by lokesh1233** [alephdata/convert-document#9]
after converting word to pdf.
the document name it is displaying as 'Ahmed Yousry'
how to change it

**Comment by pudo** [comment]
Can you give any further info, e.g. share the document in question? We do metadata extraction before we convert to PDF, so it doesn't usually show up that way in Aleph.

**Comment by lokesh1233** [comment]
Issue is resolved.
the problem is not with convert-document but with word document before converting.

Thanks for the help.
Lokesh
